# Generated by Django 5.1.5 on 2025-01-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatus',
            name='profile',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
