# Generated by Django 5.1.5 on 2025-01-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountstatus_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatus',
            name='profile',
            field=models.ImageField(blank=True, default='account/default.jpeg', null=True, upload_to=''),
        ),
    ]
