# Generated by Django 5.1.5 on 2025-01-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_accountstatus_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatus',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
