# Generated by Django 5.1.5 on 2025-02-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_accountstatus_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatus',
            name='rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
