# Generated by Django 5.1.5 on 2025-02-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_accountstatus_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatus',
            name='rank',
            field=models.CharField(blank=True, default='Silver', max_length=20),
        ),
    ]
