# Generated by Django 5.1.5 on 2025-01-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_rename_subscriber_name_subscription_subscriber_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscriber_email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
