# Generated by Django 5.1.5 on 2025-01-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='expires_at',
        ),
    ]
