# Generated by Django 5.1.5 on 2025-01-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0011_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
