# Generated by Django 5.1.5 on 2025-01-25 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0012_alter_subscription_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expires_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 24, 1, 47, 46, 123201), null=True),
        ),
    ]
