# Generated by Django 5.1.5 on 2025-01-25 03:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0014_alter_subscription_expires_at'),
        ('writer', '0013_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_favorite', to='writer.article'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 24, 3, 53, 52, 303662), null=True),
        ),
    ]
