# Generated by Django 5.1.5 on 2025-01-25 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0017_alter_subscription_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 24, 4, 15, 42, 857910), null=True),
        ),
    ]
