# Generated by Django 5.1.5 on 2025-02-01 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0022_alter_subscription_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 3, 4, 21, 49, 526100), null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='paypal_subscription_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
