# Generated by Django 5.1.5 on 2025-02-01 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0023_alter_subscription_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 3, 15, 57, 42, 79585), null=True),
        ),
    ]
