# Generated by Django 5.1.5 on 2025-02-02 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0025_alter_subscription_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 4, 9, 44, 32, 308922), null=True),
        ),
    ]
