# Generated by Django 5.1.5 on 2025-02-09 09:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0028_alter_subscription_expires_at'),
        ('writer', '0019_remove_article_rank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writer.article'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 11, 9, 59, 10, 524739), null=True),
        ),
    ]
