# Generated by Django 5.1.5 on 2025-02-09 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0029_alter_favorite_article_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 11, 10, 1, 2, 326240), null=True),
        ),
    ]
