# Generated by Django 5.1.5 on 2025-02-18 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0036_alter_subscription_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2025, 3, 20, 12, 24, 36, 798396),
                null=True,
            ),
        ),
    ]
