# Generated by Django 5.1.5 on 2025-02-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0037_alter_subscription_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
