"""
Django settings for pentagon project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2#t-+d7rd(u#*2by^=!kw0-84=$%*1kn&%ars0w=jw!w4^9rdf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']


# ALLOWED_HOSTS = ['*']
# CSRF_TRUSTED_ORIGINS = ['*']

# Application definition
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
    'reader',
    'writer',
    'django_auto_logout',
    'crispy_forms',
    'crispy_daisyui',
    'django_recaptcha',
    'fontawesomefree',
    'channels',

]
CHANNEL_LAYERS = {
    'default': {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

CRISPY_ALLOWED_TEMPLATE_PACKS = 'daisyui'
CRISPY_TEMPLATE_PACK = 'daisyui'
RECAPTCHA_PUBLIC_KEY="6Lfmc70qAAAAAP3caI9XFmfsFlGfGi4vkkZdM11i"
RECAPTCHA_PRIVATE_KEY = '6Lfmc70qAAAAABFrH2aLKA0b590RTUqR6z5MiQv0'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auto_logout.middleware.auto_logout',


]

ROOT_URLCONF = 'pentagon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auto_logout.context_processors.auto_logout_client',

            ],
        },
    },
]

WSGI_APPLICATION = 'pentagon.wsgi.application'
ASGI_APPLICATION = 'pentagon.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
from datetime import timedelta

AUTO_LOGOUT = {
    'IDLE_TIME': timedelta(minutes=30),
    'SESSION_TIME': timedelta(minutes=30),
    'MESSAGE': 'The session has expired. Please login again to continue.',
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
}
SECURE_CROSS_ORIGIN_OPENER_POLICY="same-origin-allow-popups"


AWS_ACCESS_KEY_ID='AKIASVLKCIYWJU5E6NRX'

AWS_SECRET_ACCESS_KEY='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'

EMAIL_BACKEND = "django_ses.SESBackend"

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'


AWS_SES_REGION_NAME = "ap-southeast-2"
AWS_SES_REGION_ENDPOINT = "email.ap-southeast-2.amazonaws.com"

DEFAULT_FROM_EMAIL = 'dbodbo086@gmail.com'

SITE_URL='http://127.0.0.1:8000'

CELERY_BEAT_SCHEDULE = {
    'delete_expired_subscriptions': {
        'task': 'reader.tasks.delete_expired_subscriptions',
        'schedule': 60, 
    },
    'update_user_rank':{
        "task": "writer.tasks.update_user_rank",
        'schedule':30
    },
    
    
}
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True 
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'max_retries': 5,  
    'interval_start': 0,  
    'interval_step': 30,  
    'interval_max': 30,  
}


CELERY_TASK_TIME_LIMIT = 10
CELERY_ACKS_LATE = True  
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'