# Generated by Django 5.1.5 on 2025-01-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0002_article_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlereview',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
