# Generated by Django 5.1.5 on 2025-01-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0003_alter_articlereview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, default='article/default.jpeg', null=True, upload_to=''),
        ),
    ]
