# Generated by Django 5.1.5 on 2025-01-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0005_alter_articlereview_article_alter_articlereview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, default='article/default.jpeg', null=True, upload_to='media/article'),
        ),
    ]
