# Generated by Django 5.1.5 on 2025-01-21 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0006_alter_article_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(40, message='Content must be at least 40 characters long.')]),
        ),
    ]
