# Generated by Django 5.1.5 on 2025-01-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0007_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, default='article/default.jpeg', null=True, upload_to='article/'),
        ),
    ]
