# Generated by Django 5.1.5 on 2025-01-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0009_articlecollection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleCollection',
        ),
    ]
