# Generated by Django 5.1.5 on 2025-01-25 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0014_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writer.article'),
        ),
    ]
