# Generated by Django 5.1.5 on 2025-01-25 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0016_alter_favorite_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
