# Generated by Django 5.1.5 on 2025-02-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0017_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
