# Generated by Django 5.1.5 on 2025-02-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0018_article_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rank',
        ),
    ]
