# Generated by Django 5.1.5 on 2025-02-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0020_recentarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentarticle',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
