# Generated by Django 5.1.5 on 2025-02-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writer", "0021_alter_recentarticle_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlereview",
            name="author_reply",
            field=models.TextField(blank=True, null=True),
        ),
    ]
