# Generated by Django 5.1.5 on 2025-03-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("writer", "0025_usernotification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecentArticle",
        ),
    ]
