# Generated by Django 5.1.5 on 2025-03-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("writer", "0028_alter_article_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ArticleCollection",
        ),
    ]
