# Generated by Django 5.1.5 on 2025-03-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("writer", "0029_delete_articlecollection"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserNotification",
        ),
    ]
